; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.15"

; Modules
projects[ctools][version] = "1.2"

projects[bundle_copy][version] = "1.1"

projects[compass][version] = "1.0-beta1"

projects[devel][version] = "1.3"

projects[email][version] = "1.2"

projects[entity][version] = "1.0-rc3"

projects[entityreference][version] = "1.0-rc3"

projects[features][version] = "1.0"

projects[field_validation][version] = "2.1"

projects[filecache][version] = "1.0-beta2"

projects[jquery_update][version] = "2.2"

projects[link][version] = "1.0"

projects[markdown][version] = "1.0"
projects[maxlength][version] = "3.0-beta1"

projects[panels][version] = "3.3"

projects[registration][version] = "1.0-beta3"

projects[rules][version] = "2.2"

projects[stringoverrides][version] = "1.8"

projects[strongarm][version] = "2.0"

projects[unique_field][version] = "1.0-rc1"

projects[uuid][version] = "1.x-dev"
projects[uuid_features][version] = "1.x-dev"

projects[views][version] = "3.5"

projects[views_data_export][version] = "3.0-beta6"

; Themes
projects[zen][version] = "5.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[smash_minisite_theme][download][type] = ""
projects[smash_minisite_theme][download][url] = ""
projects[smash_minisite_theme][type] = "theme"


