<?php
/**
 * @file
 * Code for the SMASH Vendors Base feature.
 */

include_once 'smash_vendors_base.features.inc';

/**
 * Loads AJAX for homepage
 */
function smash_vendors_base_init() {
  $path = request_path();
  if ($path == '' || $path == 'application' || strpos($path, 'application') === 0) {
    drupal_add_library('system', 'drupal.ajax');
  }
}

/**
* Implementation of hook_menu().
*/
function smash_vendors_base_menu() {
  $items = array();
  
  $items['request/application/%'] = array(
    'page callback' => 'smash_vendors_base_get_view',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK, 
  );

  return $items;
}

/**
 * JS callback for job list
 */
function smash_vendors_base_get_view() {
  $args = func_get_args();
  
  $title = NULL;
  $type = NULL;
  if (count($args) > 1) {
    $title = array_pop($args);
  }
  if (count($args) > 0) {
    $type = array_pop($args);
  }
  
  if ($type == 'ajax') {
    $commands = array();
    
    $pos_elems = '.ajax-result-pane-form-display > .pane-content > *';
    
    if (!empty($title)) {
      $commands[] = ajax_command_replace($des_elems, views_embed_view('application_form', 'page', $title));
    }
    else {
      $commands[] = ajax_command_replace($pos_elems, views_embed_view('application_form', 'page'));
    }

    $page = array('#type' => 'ajax', '#commands' => $commands);
    ajax_deliver($page);
  }
  else {
    if (!is_null($title)) {
      drupal_goto('application/' . $title);
    }
    else {
      drupal_goto('application');
    }
  }
}

/**
 * Alter rego form
 */
function smash_vendors_base_form_registration_form_alter(&$form, &$form_state, $form_id) {
  if (count($form['who_is_registering']['#options']) == 1) {
    $keys = array_keys($form['who_is_registering']['#options']);
    $form['who_is_registering']['#type']  = 'value';
    $form['who_is_registering']['#value'] = $keys[0];
  }
  
  $form['actions']['submit']['#value'] = t('Register');
  unset($form['actions']['cancel']);
  
  $form['#submit'][] = 'smash_vendors_base_registration_form_postsubmit';
}

function smash_vendors_base_registration_form_postsubmit($form, &$form_state) {
  // @TODO: better thank you message.
  $form_state['redirect'] = '<front>';
}
